name: bang
favicon: null
layout_spectrum: 0.5027944431640208
typography_spectrum: 0.36208265530876815
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.3651031325571239
  lightness: 0.7993471103254706
  saturation: 0.32547105196863413
  rhythmicContrast: 0.44349208660423756
purpose: []
